services:
  _defaults:
    public: false
    autowire: true
    bind:
      OxidEsales\Eshop\Core\Config: '@=service("OxidEsales\\MediaLibrary\\Core\\Registry").getConfig()'

  OxidEsales\MediaLibrary\Media\Service\MediaResourceInterface:
    class: OxidEsales\MediaLibrary\Media\Service\MediaResource
    public: true

  OxidEsales\MediaLibrary\Media\Service\MediaServiceInterface:
    class: OxidEsales\MediaLibrary\Media\Service\MediaService
    public: true

  OxidEsales\MediaLibrary\Media\Service\FrontendMediaFactoryInterface:
    class: OxidEsales\MediaLibrary\Media\Service\FrontendMediaFactory
    public: true

  OxidEsales\MediaLibrary\Media\Service\ValidatorStrategyServiceInterface:
    class: OxidEsales\MediaLibrary\Media\Service\ValidatorStrategyService
    public: true
    arguments:
      $fileNameValidatorChain: '@OxidEsales\MediaLibrary\Validation\Service\FileNameValidatorChainInterface'
      $directoryNameValidatorChain: '@OxidEsales\MediaLibrary\Validation\Service\DirectoryNameValidatorChainInterface'
