services:
  _defaults:
    public: false
    autowire: true

  OxidEsales\MediaLibrary\Validation\Service\DirectoryNameValidatorChainInterface:
    class: OxidEsales\MediaLibrary\Validation\Service\DocumentNameValidatorChain
    public: true
    arguments:
      $fileValidators:
        - '@OxidEsales\MediaLibrary\Validation\Validator\FileNameValidator'

  OxidEsales\MediaLibrary\Validation\Service\FileNameValidatorChainInterface:
    class: OxidEsales\MediaLibrary\Validation\Service\DocumentNameValidatorChain
    public: true
    arguments:
      $fileValidators:
        - '@OxidEsales\MediaLibrary\Validation\Validator\FileNameValidator'
        - '@OxidEsales\MediaLibrary\Validation\Validator\FileExtensionValidator'

  OxidEsales\MediaLibrary\Validation\Service\UploadedFileValidatorChainInterface:
    class: OxidEsales\MediaLibrary\Validation\Service\UploadedFileValidatorChain
    public: true
    arguments:
      $fileValidators: !tagged_iterator oxid_esales.media_library.validation.chain_validator
