services:
  _defaults:
    public: false
    autowire: true

  OxidEsales\MediaLibrary\Validation\Format\FileFormatRegistryInterface:
    class: OxidEsales\MediaLibrary\Validation\Format\FileFormatRegistry
