install_shop_with_modules:
  cache:
    prepared_shop: false
  composer:
    transform: |
      {
          "require": {
              "oxid-esales/oxideshop-ce": "{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/twig-component": "{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/twig-admin-theme": "{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/apex-theme": "{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/developer-tools": "{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/media-library-module": "dev-{{ .Github.RefName }}"
          },
          "repositories": {
            "oxid-esales/media-library-module": {
              "type": "git",
              "url": "https://github.com/OXID-eSales/media-library-module.git"
            }
          }
      }
  custom_script_container: |
    vendor/bin/oe-console oe:database:reset --db-host=mysql --db-port=3306 --db-name=example --db-user=root --db-password=root --force
    vendor/bin/oe-console oe:module:activate ddoemedialibrary
    vendor/bin/oe-console oe:theme:activate apex

runscript: &runscript
  matrix:
    script: |
      [
        "medialibrary:tests-unit",
        "medialibrary:tests-integration",
        "medialibrary:tests-codeception"
      ]
  medialibrary:
    path: 'vendor/oxid-esales/media-library-module'
  composer:
    early: true

runslim:
  <<: *runscript
  matrix:
    script: |
      [
        "medialibrary:phpstan",
        "medialibrary:phpcs",
      ]

sonarcloud:
  matrix:
    testplan: '["-"]'
  strip_path: '/var/www/vendor/oxid-esales/media-library-module/'
  project_key: 'OXID-eSales_media-library-module'
  project_name: 'oxid-esales/media-library-module'
  parameters: |
    -Dsonar.language=php
    -Dsonar.scm.provider=git
    -Dsonar.sources=src
    -Dsonar.tests=tests
    -Donar.php.phpstan.reportPaths=coverage-reports/phpstan.report.json

finish:
  slack_title: 'Media Library module ({{ .Data.global.git.shop_ref }}) by {{ .Github.Actor }}'
