services:
  _defaults:
    public: false
    autowire: true

  OxidEsales\MediaLibrary\Media\Settings\FallbackMediaSettingsInterface:
    class: OxidEsales\MediaLibrary\Media\Settings\FallbackMediaSettings
