imports:
  - { resource: RequestData/services.yaml }

services:
  _defaults:
    public: false
    autowire: true
    bind:
      OxidEsales\Eshop\Core\Request: '@=service("OxidEsales\\MediaLibrary\\Core\\Registry").getRequest()'
      OxidEsales\Eshop\Core\Utils: '@=service("OxidEsales\\MediaLibrary\\Core\\Registry").getUtils()'

  OxidEsales\MediaLibrary\Transput\RequestInterface:
    class: OxidEsales\MediaLibrary\Transput\Request

  OxidEsales\MediaLibrary\Transput\ResponseInterface:
    class: OxidEsales\MediaLibrary\Transput\Response
    public: true
