services:
  _defaults:
    public: false
    autowire: true

  OxidEsales\MediaLibrary\Media\Repository\MediaRepositoryInterface:
    class: OxidEsales\MediaLibrary\Media\Repository\MediaRepository
    public: true

  OxidEsales\MediaLibrary\Media\Repository\MediaFactoryInterface:
    class: OxidEsales\MediaLibrary\Media\Repository\MediaFactory

  OxidEsales\MediaLibrary\Media\Repository\PreloadMediaRepositoryInterface:
    class: OxidEsales\MediaLibrary\Media\Repository\PreloadMediaRepository
    public: true

  OxidEsales\MediaLibrary\Media\Repository\MediaAltRepositoryInterface:
    class: OxidEsales\MediaLibrary\Media\Repository\MediaAltRepository
    public: false
