services:
  _defaults:
    public: false
    autowire: true

  OxidEsales\MediaLibrary\Image\Sanitizer\SvgValidatorInterface:
    class: OxidEsales\MediaLibrary\Image\Sanitizer\SvgValidator
    arguments:
      $detectors:
        - '@OxidEsales\MediaLibrary\Image\Sanitizer\Detector\ScriptElementDetector'
        - '@OxidEsales\MediaLibrary\Image\Sanitizer\Detector\ForeignObjectDetector'
        - '@OxidEsales\MediaLibrary\Image\Sanitizer\Detector\EventHandlerDetector'
        - '@OxidEsales\MediaLibrary\Image\Sanitizer\Detector\ScriptableUrlDetector'

  OxidEsales\MediaLibrary\Image\Sanitizer\Detector\ScriptElementDetector: ~
  OxidEsales\MediaLibrary\Image\Sanitizer\Detector\ForeignObjectDetector: ~
  OxidEsales\MediaLibrary\Image\Sanitizer\Detector\EventHandlerDetector: ~
  OxidEsales\MediaLibrary\Image\Sanitizer\Detector\ScriptableUrlDetector: ~
