services:
  _defaults:
    public: false
    autowire: true

  OxidEsales\MediaLibrary\Compatibility\Repository\PathMappingRepositoryInterface:
    class: OxidEsales\MediaLibrary\Compatibility\Repository\PathMappingRepository

  OxidEsales\MediaLibrary\Compatibility\Factory\MediaFileInformationFactoryInterface:
    class: OxidEsales\MediaLibrary\Compatibility\Factory\MediaFileInformationFactory
