name: Schedule for full matrix run

on:
  schedule:
    - cron: '0 0 */7 * *'

jobs:
  schedule_matrix:
    uses: oxid-eSales/github-actions/.github/workflows/universal_workflow_light.yml@v4
    with:
      testplan: '~/defaults/7.1.x.yml,~/module-medialibrary.yml'
      runs_on: '"ubuntu-latest"'
      defaults: 'v4'
      plan_folder: '.github/oxid-esales'
      custom_testplan_yaml: |
        global:
          title: 'php81_mysql80-{{ .Github.EventName }}-{{ .Github.RefName }}'
    secrets:
      DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      CACHE_ENDPOINT: ${{ secrets.CACHE_ENDPOINT }}
      CACHE_ACCESS_KEY: ${{ secrets.CACHE_ACCESS_KEY }}
      CACHE_SECRET_KEY: ${{ secrets.CACHE_SECRET_KEY }}
      enterprise_github_token: ${{ secrets.enterprise_github_token }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
