imports:
  - { resource: Repository/services.yaml }
  - { resource: Service/services.yaml }
  - { resource: Settings/services.yaml }
  - { resource: Twig/services.yaml }
  - { resource: Controller/services.yaml }

services:
  _defaults:
    public: false
    autowire: true

  OxidEsales\MediaLibrary\Media\Facade\MediaFacadeInterface:
    class: OxidEsales\MediaLibrary\Media\Facade\MediaFacade
    public: true

  OxidEsales\MediaLibrary\Media\Facade\FallbackMediaFacadeDecorator:
    decorates: OxidEsales\MediaLibrary\Media\Facade\MediaFacadeInterface
